live_config_reload = true

[font]
size = 20

[font.normal]
family = "Hack mono"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
opacity = 1

[window.padding]
x = 10
y = 10

[scrolling]
history = 12000

[[keyboard.bindings]]
key = "I"
mods = "Control | Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "U"
mods = "Control"
mode = "Vi"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control"
mode = "Vi"
action = "ScrollHalfPageDown"
