set -g mode-style "fg=#232136,bg=#c4a7e7"
set -g message-style "fg=#232136,bg=#c4a7e7"
set -g message-command-style "fg=#232136,bg=#c4a7e7"

set -ug status-format
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-style "fg=#6e6a86,bg=#232136"
set -g status-bg "#232136"

set -g status-left-length 140
set -g status-right-length 160
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#{?client_prefix,#[bg=#f6c177],#[bg=#b4b1c8]}#[fg=#232136,bold] #S #[fg=#908caa,bg=#393552,nobold] #(~/.config/bin/tmux-status-git '#{pane_current_path}') #[default] "
set -g status-right "#(~/.config/bin/tmux-status-sys '#{@cctask_role}' '#{pane_current_command}')"

setw -g window-status-activity-style "underscore,fg=#908caa,bg=#232136"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#6e6a86,bg=#232136"
setw -g window-status-format " #[fg=#6e6a86]#I #[fg=#908caa]#W#(~/.config/bin/cctask-claude-status #{window_id})#{?#{@cctask_editor_hidden}, #[fg=#f6c177]nvim off,}#{?#{@cctask_shell_hidden}, #[fg=#f6c177]shell off,} "
setw -g window-status-current-format "#[fg=#232136,bg=#c4a7e7] #I #W#(~/.config/bin/cctask-claude-status #{window_id})#{?#{@cctask_editor_hidden}, nvim off,}#{?#{@cctask_shell_hidden}, shell off,} #[default]"
